#!/bin/sh
#
# Construct new Sword module from Ulrik
# Petersen's re-Greek-ified text, v1.1.
#
f=strongsrealgreek.imp
#
sed -e 's/><entry strongs/>\r<entry strongs/' < strongsgreek.xml | tr '\r' '\n' > $f
mv $f $f.1
sed -e '1,/<entries>/d' -e '/<\/entries>/,$d' -e '/<\/entry>/d' < $f.1 > $f
mv $f $f.2
sed -e 's;<entry strongs="\([0-9]\+\)">;$$$\1;g' < $f.2 \
    -e 's;<strongs>\([0-9]\+\)</strongs>;<a name="\1"><b>\1</b></a>;g' \
    -e 's;<strongsref language="GREEK" strongs="\([0-9]\+\)"/>;<a href="sword://StrongsRealGreek/\1">\1</a>;g' \
    -e 's;<strongsref language="HEBREW" strongs="\([0-9]\+\)"/>;<a href="sword://StrongsRealHebrew/\1">\1</a>;g' \
    -e 's;<greek BETA="\([^"]\+\)" unicode="\([^"]\+\)"/>;\2 [\1];g' \
    -e 's;</\?\(strongs_\(derivation\|def\)\|kjv_def\)>;;g' \
    -e 's|<pronunciation strongs="\([^"]\+\)" */>\([,;] *\)\?|\\<i>\1</i>\\<br />|g' \
    -e 's;<see language="GREEK" strongs="\([0-9]\+\)"/>;<br />See Greek <a href="sword://StrongsRealGreek/\1">\1</a>.;g' \
    -e 's;<see language="HEBREW" strongs="\([0-9]\+\)"/>;<br />See Hebrew <a href="sword://StrongsRealHebrew/\1">\1</a>.;g' \
    -e 's;\(href="sword://StrongsReal\(Greek\|Hebrew\)/\|name="\)\([0-9]\)";\10\3";g' \
    -e 's;\(href="sword://StrongsReal\(Greek\|Hebrew\)/\|name="\)\([0-9][0-9]\)";\10\3";g' \
    -e 's;\(href="sword://StrongsReal\(Greek\|Hebrew\)/\|name="\)\([0-9][0-9][0-9]\)";\10\3";g' \
    -e 's;\(href="sword://StrongsReal\(Greek\|Hebrew\)/\|name="\)\([0-9][0-9][0-9][0-9]\)";\10\3";g' \
    -e 's;^ *;;g' \
    -e '/^ *$/d' \
    -e 's;$; ;' \
    -e '/^\$\$\$/s; $;;' > $f
imp2ld strongsrealgreek.imp
chmod go+r strongsrealgreek.dat strongsrealgreek.idx
exit 0
